name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Build and Push Docker Image to ECR
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Branch and Commit Hash
        id: git-info
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          HASH=$(git rev-parse --short HEAD)
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "HASH=$HASH" >> $GITHUB_ENV

      - name: Log in to Amazon ECR
        env:
          AWS_REGION: us-east-1
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}

      - name: Build Docker image
        run: |
          cd Docker
          docker build -t darede .

      - name: Docker Tag with Branch and Commit Hash
        run: |
          docker tag darede:latest ${{ secrets.ECR_URI }}:${{ env.BRANCH }}-${{ env.HASH }}
          docker tag darede:latest ${{ secrets.ECR_URI }}:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_URI }}:${{ env.BRANCH }}-${{ env.HASH }}
          docker push ${{ secrets.ECR_URI }}:latest

  # Job 2: Snyk Security Scan
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Branch and Commit Hash
        id: git-info
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          HASH=$(git rev-parse --short HEAD)
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "HASH=$HASH" >> $GITHUB_ENV

      - name: Log in to Amazon ECR
        env:
          AWS_REGION: us-east-1
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}

      - name: Pull Docker image from ECR
        run: |
          docker pull ${{ secrets.ECR_URI }}:${{ env.BRANCH }}-${{ env.HASH }}

      - name: Install Snyk CLI
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npm install -g snyk
          snyk auth $SNYK_TOKEN

      - name: Snyk Docker Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk container test ${{ secrets.ECR_URI }}:${{ env.BRANCH }}-${{ env.HASH }} || true
        shell: bash

  # Job 3: Terraform Apply
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Branch and Commit Hash
        id: git-info
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          HASH=$(git rev-parse --short HEAD)
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "HASH=$HASH" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
           aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}
